# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7z020clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/BitBucketLocalRepository/verilog-projects/8_Bit_Processor/8Bit_uC/8Bit_uC.cache/wt [current_project]
set_property parent.project_path D:/BitBucketLocalRepository/verilog-projects/8_Bit_Processor/8Bit_uC/8Bit_uC.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part tul.com.tw:pynq-z2:part0:1.0 [current_project]
set_property ip_output_repo d:/BitBucketLocalRepository/verilog-projects/8_Bit_Processor/8Bit_uC/8Bit_uC.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  D:/BitBucketLocalRepository/verilog-projects/8_Bit_Processor/8Bit_uC/8Bit_uC.srcs/sources_1/imports/sources_1/imports/8_Bit_Processor/8Bit_Multiplier/8Bit_Multiplier.srcs/sources_1/new/Adder_1Bit.v
  D:/BitBucketLocalRepository/verilog-projects/8_Bit_Processor/8Bit_uC/8Bit_uC.srcs/sources_1/imports/sources_1/imports/8_Bit_Processor/8Bit_Multiplier/8Bit_Multiplier.srcs/sources_1/new/Adder_8Bit.v
  D:/BitBucketLocalRepository/verilog-projects/8_Bit_Processor/8Bit_uC/8Bit_uC.srcs/sources_1/imports/new/Comparator_4Bit.v
  D:/BitBucketLocalRepository/verilog-projects/8_Bit_Processor/8Bit_uC/8Bit_uC.srcs/sources_1/imports/new/ControlPath.v
  D:/BitBucketLocalRepository/verilog-projects/8_Bit_Processor/8Bit_uC/8Bit_uC.srcs/sources_1/imports/new/ControlPath_Multiplier.v
  D:/BitBucketLocalRepository/verilog-projects/8_Bit_Processor/8Bit_uC/8Bit_uC.srcs/sources_1/imports/new/DataPath.v
  D:/BitBucketLocalRepository/verilog-projects/8_Bit_Processor/8Bit_uC/8Bit_uC.srcs/sources_1/imports/new/DataSelector_4bit.v
  D:/BitBucketLocalRepository/verilog-projects/8_Bit_Processor/8Bit_uC/8Bit_uC.srcs/sources_1/imports/new/DataSelector_nBit.v
  D:/BitBucketLocalRepository/verilog-projects/8_Bit_Processor/8Bit_uC/8Bit_uC.srcs/sources_1/imports/new/Datapath_Multiplier.v
  D:/BitBucketLocalRepository/verilog-projects/8_Bit_Processor/8Bit_uC/8Bit_uC.srcs/sources_1/imports/new/Divider_4Bit.v
  D:/BitBucketLocalRepository/verilog-projects/8_Bit_Processor/8Bit_uC/8Bit_uC.srcs/sources_1/imports/new/LoadAndCountDownRegister_nBit.v
  D:/BitBucketLocalRepository/verilog-projects/8_Bit_Processor/8Bit_uC/8Bit_uC.srcs/sources_1/imports/new/LoadRegister_16Bit_Mul.v
  D:/BitBucketLocalRepository/verilog-projects/8_Bit_Processor/8Bit_uC/8Bit_uC.srcs/sources_1/imports/new/LoadRegister_4bit.v
  D:/BitBucketLocalRepository/verilog-projects/8_Bit_Processor/8Bit_uC/8Bit_uC.srcs/sources_1/imports/new/Multiplier_8Bit.v
  D:/BitBucketLocalRepository/verilog-projects/8_Bit_Processor/8Bit_uC/8Bit_uC.srcs/sources_1/imports/new/NorGate_nBit.v
  D:/BitBucketLocalRepository/verilog-projects/8_Bit_Processor/8Bit_uC/8Bit_uC.srcs/sources_1/imports/sources_1/imports/8_Bit_Processor/8Bit_Divider/8Bit_Divider.srcs/sources_1/imports/4_Bit_Divider.srcs/sources_1/new/Substractor_1Bit.v
  D:/BitBucketLocalRepository/verilog-projects/8_Bit_Processor/8Bit_uC/8Bit_uC.srcs/sources_1/imports/sources_1/imports/8_Bit_Processor/8Bit_Divider/8Bit_Divider.srcs/sources_1/imports/4_Bit_Divider.srcs/sources_1/new/Substractor_4bit.v
  D:/BitBucketLocalRepository/verilog-projects/8_Bit_Processor/8Bit_uC/8Bit_uC.srcs/sources_1/imports/new/UpCounter_4Bit.v
  D:/BitBucketLocalRepository/verilog-projects/8_Bit_Processor/8Bit_uC/8Bit_uC.srcs/sources_1/new/uC_8Bit.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top uC_8Bit -part xc7z020clg400-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef uC_8Bit.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file uC_8Bit_utilization_synth.rpt -pb uC_8Bit_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
